POST http://localhost:5000/users/login
Content-type: application/json

{
  "email": "visitor@mail.com",
  "password" : "password123"
}

###
POST http://localhost:5000/users
Content-type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "email": "johndoe1@email.com",
  "password": "password123"
}

###
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY3MjgzNzAwOSwiZXhwIjoxNjcyODQwNjA5fQ.RCziwBPzV54HcoiTglyeTZ3ijXLhEj6_qnNZakGQIbE